services:
  app:
    build:
      context: .
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - TZ=${TIMEZONE}
