# fly.toml app configuration file generated for woovi-backend-delicate-waterfall-5753 on 2024-07-24T20:39:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'woovi-backend-delicate-waterfall-5753'
primary_region = 'gru'

[build]

[env]
  JWT_AUDIENCE = 'mybank'
  JWT_EXPIRES_IN = '3600000'
  JWT_SECRET = 'jJf1R4H$xZv0Tq1L!n7eP8Qr5Ys2Bw9E'
  MONGO_DATABASE = 'mybank'
  MONGO_HOST = 'mongo'
  MONGO_PASSWORD = '123456'
  MONGO_PORT = '27017'
  MONGO_USERNAME = 'root'
  NODE_ENV = 'production'
  NODE_PORT = '4000'
  TIMEZONE = 'America/Sao_Paulo'
  GRAPHQL_URL  = 'https://woovi-backend-delicate-waterfall-5753.fly.dev/graphql'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
